name: general-preprocessing-rainfall_noaa
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - python=3.9
  - pandas
  - xarray
  - iris
  - cf-units
  - geoviews
  - pip
  - pip:
      - nc_time_axis