name: ea34568e-d86e-4720-be2f-3f826f66a26c
channels:
  - conda-forge
  - pyviz
  - nodefaults
dependencies:
  - python=3.9
  - pandas
  - xarray
  - iris==3.2.1
  - cf-units
  - geoviews
  - pip
  - pip:
      - nc_time_axis